import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./compoments/header";
import FunctionList from "./compoments/function-list";
import MusicPlayer from "./compoments/music-player";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "music",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="flex">
          <FunctionList />
          <main className=" w-5/6 ">
            {children}
          </main>
        </div>
        <MusicPlayer />
      </body>
    </html>

  );
}
